apiVersion: apps/v1
kind: Deployment
metadata:
  name: c8y-tracker-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: c8y-tracker-agent
  template:
    metadata:
      labels:
        app: c8y-tracker-agent
    spec:
      containers:
      - name: c8y-tracker-agent
        image: tcp-agent:1.0  # Replace with your Docker image
        env:
        - name: C8Y_BOOTSTRAP_TENANT  # Add your environment variables here
          value: "t11974744"  # Example value for MY_ENV_VAR
        ports:
        - containerPort: 8888  # TCP Port exposed inside the container
        - containerPort: 8080  # HTTP Port exposed inside the container
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: c8y-tracker-agent-service
spec:
  selector:
    app: c8y-tracker-agent
  ports:
    - protocol: TCP
      port: 8888   # Port exposed by the service
      targetPort: 8888  # Internal port inside the container
      name: tcp
      nodePort: 30000
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
      nodePort: 30001
  type: NodePort
