name: Java Microservice Build

on:
  push:
    tags:
      - '*'   # Trigger on any tag creation

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up JDK
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # 3. Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # 4. Build & run unit tests
    - name: Build and run tests
      run: mvn clean test package --batch-mode


    # 5. Build Docker image and save as versioned tar
    - name: Build Docker image
      run: |
        VERSION=${GITHUB_REF_NAME#refs/tags/}   # Extract tag name
        docker build -t tcp-agent:$VERSION -f target/docker-work/Dockerfile target/docker-work
        docker save tcp-agent:$VERSION -o tcp-agent-$VERSION.tar

    # 6a. Upload JAR artifact
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: microservice-jar
        path: target/*.jar

    # 6b. Upload ZIP artifact
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: microservice-zip
        path: target/*.zip

    # 6c. Upload Docker tar artifact
    - name: Upload Docker image tar
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-tar
        path: tcp-agent-*.tar

    # 7. Upload test reports
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/*.xml
